-- ============================================================
-- COMPLETE SQL FOR DOCUMENT MONITORING SYSTEM (NO SAMPLE DATA)
-- Includes: tables, RLS policies, triggers, views, functions
-- ============================================================

-- ============================================================
-- 1. CREATE THE OFFICES TABLE (referenced by documents)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.offices (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL UNIQUE,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Add index for offices
CREATE INDEX IF NOT EXISTS idx_offices_name ON public.offices (name);

-- ============================================================
-- 2. CREATE THE DOCUMENTS TABLE (from your document receive system)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.documents (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date         DATE NOT NULL,
  office_id    BIGINT NOT NULL REFERENCES public.offices(id) ON DELETE CASCADE,
  time         TIME NOT NULL,
  description  TEXT NOT NULL,
  received     TEXT DEFAULT '',
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Add indexes for documents
CREATE INDEX IF NOT EXISTS idx_documents_date ON public.documents (date);
CREATE INDEX IF NOT EXISTS idx_documents_office_id ON public.documents (office_id);
CREATE INDEX IF NOT EXISTS idx_documents_description ON public.documents (description);

-- ============================================================
-- 3. CREATE THE MONITORING TABLE (for daily monitoring)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.monitoring (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description  TEXT NOT NULL,
  date         DATE NOT NULL,
  followup     TEXT NOT NULL,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Add indexes for monitoring
CREATE INDEX IF NOT EXISTS idx_monitoring_description ON public.monitoring (description);
CREATE INDEX IF NOT EXISTS idx_monitoring_date ON public.monitoring (date);
CREATE INDEX IF NOT EXISTS idx_monitoring_description_date ON public.monitoring (description, date);

-- ============================================================
-- 4. ENABLE ROW LEVEL SECURITY
-- ============================================================

-- Enable RLS on all tables
ALTER TABLE public.offices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monitoring ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 5. CREATE RLS POLICIES FOR OFFICES
-- ============================================================

DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.offices;
DROP POLICY IF EXISTS "Enable read for anonymous" ON public.offices;
DROP POLICY IF EXISTS "Enable insert for anonymous" ON public.offices;
DROP POLICY IF EXISTS "Enable update for anonymous" ON public.offices;
DROP POLICY IF EXISTS "Enable delete for anonymous" ON public.offices;

CREATE POLICY "Enable all for authenticated users" ON public.offices
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable read for anonymous" ON public.offices
  FOR SELECT TO anon USING (true);

CREATE POLICY "Enable insert for anonymous" ON public.offices
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Enable update for anonymous" ON public.offices
  FOR UPDATE TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Enable delete for anonymous" ON public.offices
  FOR DELETE TO anon USING (true);

-- ============================================================
-- 6. CREATE RLS POLICIES FOR DOCUMENTS
-- ============================================================

DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.documents;
DROP POLICY IF EXISTS "Enable read for anonymous" ON public.documents;
DROP POLICY IF EXISTS "Enable insert for anonymous" ON public.documents;
DROP POLICY IF EXISTS "Enable update for anonymous" ON public.documents;
DROP POLICY IF EXISTS "Enable delete for anonymous" ON public.documents;

CREATE POLICY "Enable all for authenticated users" ON public.documents
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable read for anonymous" ON public.documents
  FOR SELECT TO anon USING (true);

CREATE POLICY "Enable insert for anonymous" ON public.documents
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Enable update for anonymous" ON public.documents
  FOR UPDATE TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Enable delete for anonymous" ON public.documents
  FOR DELETE TO anon USING (true);

-- ============================================================
-- 7. CREATE RLS POLICIES FOR MONITORING
-- ============================================================

DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.monitoring;
DROP POLICY IF EXISTS "Enable read for anonymous" ON public.monitoring;
DROP POLICY IF EXISTS "Enable insert for anonymous" ON public.monitoring;
DROP POLICY IF EXISTS "Enable update for anonymous" ON public.monitoring;
DROP POLICY IF EXISTS "Enable delete for anonymous" ON public.monitoring;

CREATE POLICY "Enable all for authenticated users" ON public.monitoring
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable read for anonymous" ON public.monitoring
  FOR SELECT TO anon USING (true);

CREATE POLICY "Enable insert for anonymous" ON public.monitoring
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Enable update for anonymous" ON public.monitoring
  FOR UPDATE TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Enable delete for anonymous" ON public.monitoring
  FOR DELETE TO anon USING (true);

-- ============================================================
-- 8. AUTO-UPDATE UPDATED_AT TRIGGER
-- ============================================================

-- Function to update updated_at column
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for offices
DROP TRIGGER IF EXISTS update_offices_updated_at ON public.offices;
CREATE TRIGGER update_offices_updated_at
  BEFORE UPDATE ON public.offices
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Triggers for documents
DROP TRIGGER IF EXISTS update_documents_updated_at ON public.documents;
CREATE TRIGGER update_documents_updated_at
  BEFORE UPDATE ON public.documents
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Triggers for monitoring
DROP TRIGGER IF EXISTS update_monitoring_updated_at ON public.monitoring;
CREATE TRIGGER update_monitoring_updated_at
  BEFORE UPDATE ON public.monitoring
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================
-- 9. CREATE VIEWS FOR EASY ACCESS
-- ============================================================

-- View for documents with office names
CREATE OR REPLACE VIEW public.documents_view AS
SELECT 
  d.id,
  d.date,
  d.office_id,
  o.name AS office_name,
  d.time,
  d.description,
  d.received,
  d.created_at,
  d.updated_at
FROM public.documents d
LEFT JOIN public.offices o ON d.office_id = o.id
ORDER BY d.date DESC, d.time DESC;

GRANT SELECT ON public.documents_view TO anon, authenticated;

-- View for monitoring summary
CREATE OR REPLACE VIEW public.monitoring_summary AS
SELECT 
  description,
  COUNT(*) AS total_records,
  MIN(date) AS first_date,
  MAX(date) AS last_date,
  COUNT(DISTINCT date) AS total_days
FROM public.monitoring
GROUP BY description
ORDER BY description ASC;

GRANT SELECT ON public.monitoring_summary TO anon, authenticated;

-- View for daily monitoring counts
CREATE OR REPLACE VIEW public.monitoring_daily AS
SELECT 
  description,
  date,
  COUNT(*) AS daily_count,
  STRING_AGG(followup, ' | ' ORDER BY id) AS followups
FROM public.monitoring
GROUP BY description, date
ORDER BY date DESC, description ASC;

GRANT SELECT ON public.monitoring_daily TO anon, authenticated;

-- ============================================================
-- 10. HELPER FUNCTIONS
-- ============================================================

-- Function to get documents by description
CREATE OR REPLACE FUNCTION public.get_documents_by_description(
  search_description TEXT
)
RETURNS SETOF public.documents_view
LANGUAGE sql
AS $$
  SELECT * FROM public.documents_view
  WHERE description ILIKE '%' || search_description || '%'
  ORDER BY date DESC;
$$;

-- Function to get monitoring by description
CREATE OR REPLACE FUNCTION public.get_monitoring_by_description(
  search_description TEXT
)
RETURNS SETOF public.monitoring
LANGUAGE sql
AS $$
  SELECT * FROM public.monitoring
  WHERE description = search_description
  ORDER BY date DESC;
$$;

-- Function to get monitoring by date range
CREATE OR REPLACE FUNCTION public.get_monitoring_by_date_range(
  start_date DATE,
  end_date DATE
)
RETURNS SETOF public.monitoring
LANGUAGE sql
AS $$
  SELECT * FROM public.monitoring
  WHERE date BETWEEN start_date AND end_date
  ORDER BY date DESC, description ASC;
$$;

-- Function to get monitoring by description and date range
CREATE OR REPLACE FUNCTION public.get_monitoring_by_description_date(
  search_description TEXT,
  start_date DATE,
  end_date DATE
)
RETURNS SETOF public.monitoring
LANGUAGE sql
AS $$
  SELECT * FROM public.monitoring
  WHERE description = search_description
    AND date BETWEEN start_date AND end_date
  ORDER BY date DESC;
$$;

-- ============================================================
-- 11. GRANT PERMISSIONS
-- ============================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated;

GRANT ALL PRIVILEGES ON public.offices TO anon, authenticated;
GRANT ALL PRIVILEGES ON public.documents TO anon, authenticated;
GRANT ALL PRIVILEGES ON public.monitoring TO anon, authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

GRANT EXECUTE ON FUNCTION public.get_documents_by_description(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_monitoring_by_description(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_monitoring_by_date_range(DATE, DATE) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_monitoring_by_description_date(TEXT, DATE, DATE) TO anon, authenticated;

-- ============================================================
-- 12. VERIFICATION QUERIES (commented out - uncomment as needed)
-- ============================================================

-- Check if tables exist
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;

-- Check if policies exist
-- SELECT tablename, policyname FROM pg_policies WHERE schemaname = 'public' ORDER BY tablename;

-- Check if functions exist
-- SELECT proname FROM pg_proc WHERE pronamespace = 'public'::regnamespace ORDER BY proname;

-- ============================================================
-- 13. OPTIONAL: DROP TABLES (use with caution!)
-- ============================================================
-- DROP TABLE IF EXISTS public.monitoring CASCADE;
-- DROP TABLE IF EXISTS public.documents CASCADE;
-- DROP TABLE IF EXISTS public.offices CASCADE;