-- ============================================================
-- 1. Create the 'offices' table (complete schema)
--    This matches the structure expected by the dashboard.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.offices (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Add an index on 'name' for faster searches (optional)
CREATE INDEX IF NOT EXISTS idx_offices_name ON public.offices (name);

-- ============================================================
-- 2. Enable Row Level Security (RLS) – recommended for Supabase
-- ============================================================

ALTER TABLE public.offices ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 3. Create RLS policies (adjust to your needs)
-- ============================================================

-- Policy: Allow all operations for authenticated users
-- (you can restrict further if needed)
CREATE POLICY "Allow all for authenticated users" ON public.offices
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Policy: Allow read-only for anonymous users (if needed)
CREATE POLICY "Allow read for anonymous" ON public.offices
  FOR SELECT
  TO anon
  USING (true);

-- ============================================================
-- 4. (Optional) Auto-update 'updated_at' column
--    Create a trigger to set updated_at on row changes
-- ============================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_offices_updated_at ON public.offices;
CREATE TRIGGER update_offices_updated_at
  BEFORE UPDATE ON public.offices
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================
-- 5. Insert sample offices (so you have data to start with)
-- ============================================================

INSERT INTO public.offices (name) VALUES
  ('Headquarters'),
  ('Branch North'),
  ('Branch South'),
  ('European Office'),
  ('Asia-Pacific HQ')
ON CONFLICT DO NOTHING;

-- ============================================================
-- 6. (Optional) Verify your data
-- ============================================================
-- SELECT * FROM public.offices ORDER BY id;