-- ============================================================
-- COMPLETE SQL FOR DOCUMENT RECEIVE MANAGEMENT (FIXED)
-- Fixed: Create offices table FIRST, then documents
-- ============================================================

-- ============================================================
-- 1. FIRST, CREATE THE OFFICES TABLE (referenced by documents)
-- ============================================================

-- Drop tables in reverse order to avoid dependency issues
DROP TABLE IF EXISTS public.documents CASCADE;
DROP TABLE IF EXISTS public.offices CASCADE;

-- Create offices table
CREATE TABLE public.offices (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL UNIQUE,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Add indexes for offices
CREATE INDEX IF NOT EXISTS idx_offices_name ON public.offices (name);

-- ============================================================
-- 2. CREATE THE DOCUMENTS TABLE (references offices)
-- ============================================================

CREATE TABLE public.documents (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date         DATE NOT NULL,
  office_id    BIGINT NOT NULL REFERENCES public.offices(id) ON DELETE CASCADE,
  time         TIME NOT NULL,
  description  TEXT NOT NULL,
  received     TEXT DEFAULT '',
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Add indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_documents_date ON public.documents (date);
CREATE INDEX IF NOT EXISTS idx_documents_office_id ON public.documents (office_id);
CREATE INDEX IF NOT EXISTS idx_documents_received ON public.documents (received);

-- ============================================================
-- 3. INSERT OFFICES FIRST (so documents can reference them)
-- ============================================================

INSERT INTO public.offices (name) VALUES
  ('Headquarters'),
  ('Branch North'),
  ('Branch South'),
  ('European Office'),
  ('Asia-Pacific HQ')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- 4. NOW INSERT SAMPLE DOCUMENTS (offices now exist)
-- ============================================================

INSERT INTO public.documents (date, office_id, time, description, received) VALUES
  (CURRENT_DATE - INTERVAL '2 days', 1, '09:30:00', 'Annual financial report Q2 2026', 'Received by John Smith at 2026-08-10 09:35:22'),
  (CURRENT_DATE - INTERVAL '1 day', 2, '14:15:00', 'Invoice #INV-2026-0042 from vendor', 'Received by Maria Garcia at 2026-08-11 14:20:15'),
  (CURRENT_DATE, 3, '10:00:00', 'Contract renewal documents for client ABC Corp', ''),
  (CURRENT_DATE - INTERVAL '3 days', 1, '16:45:00', 'Employee onboarding package - new hires', 'Received by David Chen at 2026-08-09 16:50:30'),
  (CURRENT_DATE - INTERVAL '5 days', 4, '11:20:00', 'European market research report', 'Received by Anna Kowalski at 2026-08-07 11:25:45');

-- ============================================================
-- 5. ENABLE ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.offices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 6. CREATE RLS POLICIES FOR OFFICES
-- ============================================================

DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.offices;
DROP POLICY IF EXISTS "Enable read for anonymous" ON public.offices;
DROP POLICY IF EXISTS "Enable insert for anonymous" ON public.offices;
DROP POLICY IF EXISTS "Enable update for anonymous" ON public.offices;
DROP POLICY IF EXISTS "Enable delete for anonymous" ON public.offices;

CREATE POLICY "Enable all for authenticated users" ON public.offices
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable read for anonymous" ON public.offices
  FOR SELECT TO anon USING (true);

CREATE POLICY "Enable insert for anonymous" ON public.offices
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Enable update for anonymous" ON public.offices
  FOR UPDATE TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Enable delete for anonymous" ON public.offices
  FOR DELETE TO anon USING (true);

-- ============================================================
-- 7. CREATE RLS POLICIES FOR DOCUMENTS
-- ============================================================

DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.documents;
DROP POLICY IF EXISTS "Enable read for anonymous" ON public.documents;
DROP POLICY IF EXISTS "Enable insert for anonymous" ON public.documents;
DROP POLICY IF EXISTS "Enable update for anonymous" ON public.documents;
DROP POLICY IF EXISTS "Enable delete for anonymous" ON public.documents;

CREATE POLICY "Enable all for authenticated users" ON public.documents
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable read for anonymous" ON public.documents
  FOR SELECT TO anon USING (true);

CREATE POLICY "Enable insert for anonymous" ON public.documents
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Enable update for anonymous" ON public.documents
  FOR UPDATE TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Enable delete for anonymous" ON public.documents
  FOR DELETE TO anon USING (true);

-- ============================================================
-- 8. AUTO-UPDATE UPDATED_AT TRIGGER
-- ============================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for offices
DROP TRIGGER IF EXISTS update_offices_updated_at ON public.offices;
CREATE TRIGGER update_offices_updated_at
  BEFORE UPDATE ON public.offices
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Triggers for documents
DROP TRIGGER IF EXISTS update_documents_updated_at ON public.documents;
CREATE TRIGGER update_documents_updated_at
  BEFORE UPDATE ON public.documents
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================
-- 9. CREATE VIEW FOR EASY ACCESS
-- ============================================================

CREATE OR REPLACE VIEW public.documents_view AS
SELECT 
  d.id,
  d.date,
  d.office_id,
  o.name AS office_name,
  d.time,
  d.description,
  d.received,
  d.created_at,
  d.updated_at
FROM public.documents d
LEFT JOIN public.offices o ON d.office_id = o.id
ORDER BY d.date DESC, d.time DESC;

-- Grant access to the view
GRANT SELECT ON public.documents_view TO anon, authenticated;

-- ============================================================
-- 10. GRANT PERMISSIONS
-- ============================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL PRIVILEGES ON public.offices TO anon, authenticated;
GRANT ALL PRIVILEGES ON public.documents TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- ============================================================
-- 11. HELPER FUNCTIONS (OPTIONAL)
-- ============================================================

-- Function to get documents by date range
CREATE OR REPLACE FUNCTION public.get_documents_by_date_range(
  start_date DATE,
  end_date DATE
)
RETURNS SETOF public.documents_view
LANGUAGE sql
AS $$
  SELECT * FROM public.documents_view
  WHERE date BETWEEN start_date AND end_date
  ORDER BY date DESC, time DESC;
$$;

-- Function to get documents by office
CREATE OR REPLACE FUNCTION public.get_documents_by_office(
  office_id BIGINT
)
RETURNS SETOF public.documents_view
LANGUAGE sql
AS $$
  SELECT * FROM public.documents_view
  WHERE office_id = $1
  ORDER BY date DESC, time DESC;
$$;

-- Function to get signed documents
CREATE OR REPLACE FUNCTION public.get_signed_documents()
RETURNS SETOF public.documents_view
LANGUAGE sql
AS $$
  SELECT * FROM public.documents_view
  WHERE received IS NOT NULL AND received != ''
  ORDER BY date DESC, time DESC;
$$;

-- Function to get unsigned documents
CREATE OR REPLACE FUNCTION public.get_unsigned_documents()
RETURNS SETOF public.documents_view
LANGUAGE sql
AS $$
  SELECT * FROM public.documents_view
  WHERE received IS NULL OR received = ''
  ORDER BY date DESC, time DESC;
$$;

-- ============================================================
-- 12. VERIFICATION QUERIES
-- ============================================================

-- Check offices
SELECT * FROM public.offices ORDER BY id;

-- Check documents with office names
SELECT 
  d.id,
  d.date,
  o.name AS office,
  d.time,
  d.description,
  CASE 
    WHEN d.received IS NULL OR d.received = '' THEN 'Not signed'
    ELSE d.received
  END AS received_status,
  d.created_at
FROM public.documents d
LEFT JOIN public.offices o ON d.office_id = o.id
ORDER BY d.date DESC, d.time DESC;

-- Count records
SELECT 
  (SELECT COUNT(*) FROM public.offices) AS total_offices,
  (SELECT COUNT(*) FROM public.documents) AS total_documents;

-- Show the view
SELECT * FROM public.documents_view;